#!/usr/bin/env bash

PROJECT_NAME=pnode_info_rs

set -euo pipefail

function Usage
{
    cat <<EOF
Usage: 

  #Builds a statically linked binary locally to a specific folder
  ${BASH_SOURCE[0]} bin-release --output-dir=\$(pwd)/distbin

  #Builds the project in a docker container and push it
  ${BASH_SOURCE[0]} docker-release --version

EOF
}

function BinRelease {
    local param=$1
    local outdir=$(echo $param | perl -ne 'print $1 if /--output-dir=(\S+)/')
    if [[ -n $outdir && -d "$outdir" ]]; then
      RUSTFLAGS="-C target-feature=+crt-static" \
            CARGO_BUILD_TARGET_DIR=$outdir cargo build --release
    else
       echo "\nERR: did you forget to --out-dir=/some/path ??\n"
       Usage
       return 1
    fi
}

function DockerRelease {
    local param=$1
    local version=$(echo $param | perl -ne 'print $1 if /--version=(\S+)/')
    if [[ "$param" =~ --version= ]]; then
        

        if [[ -z "$version" ]]; then
            Usage
            return 1
        fi

        git fetch
        git checkout $version
        mkdir -p distbin
        
        local builder_name=crossbuilderx
        local has_crossbuilderx="$(docker buildx ls | perl -ne 'print $1 if /^(${builder_name})/; ')"
        if [[ -z "$has_crossbuilderx" ]]; then
            docker buildx create --name ${builder_name}
        fi
        docker buildx use ${builder_name}

        export VERSION=$version
        docker buildx build --build-arg VERSION=${VERSION} \
            --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6 \
            --push -t iiping/pnode_info_rs:${VERSION} .
    
    else
      echo "did you forget to add --version=some-version ??"
      Usage
      return 1
    fi

}

function GetScriptDIR() {
    local src="${BASH_SOURCE[0]}"
    local ldir=""
    while [ -h "$src" ]; do
        ldir="$(dirname "$(realpath "$src")")"
        src="$(readlink "$src")"
        [[ $src != /* ]] && src="$ldir/$src"
    done
    ldir="$( cd -P "$( dirname "$src" )" >/dev/null 2>&1 && pwd )"
    echo "$ldir"
}


###### main


if [[ $# -le 1 ]]; then
  Usage
  exit 1
fi

cd "$(GetScriptDIR)"

action=$1
shift
params=$@




if [[ "$action" == "bin-release" ]]; then
  BinRelease $params
elif [[ "$action" == "docker-release" ]]; then
  DockerRelease $params
fi

