name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3
      - name: running build
        run: |
          cd ${{ github.workspace }}
          echo ${{ secrets.GHPUSH }} | docker login --username iiping --password-stdin
          ./build docker-release-ghaction dummy

      - run: echo "🍏 This job's status is ${{ job.status }}."
